# Generated by Django 4.2.7 on 2023-11-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkIt', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
