# Generated by Django 4.2.7 on 2023-11-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkIt', '0005_favoritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='post_images/default_image.jpg', upload_to='post_images'),
        ),
    ]
